services:
  database:
    image: 'postgres:17.4-alpine3.20'
    container_name: database
    ports:
      - "5432:5432"
    env_file:
      - .env

  adminer:
    image: adminer
    ports:
      - "8000:8080"
    depends_on:
      database:
        condition: service_started

  backend:
    build:
      context: .
      args:
        VERSION: 1.0
    container_name: backend
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - .:/node/app
      - /node/app/node_modules
