services:
  database:
    image: 'postgres:17.4-alpine3.20'
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data/"
    env_file:
      - .env

  backend:
    build:
      context: .
      args:
        VERSION: 1.0
    container_name: backend
    ports:
      - "8080:8080"

volumes:
  db: {}